=== wesleyfelipe/ormhibernate/src/main/resources/semiestruturados/Negocio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:complexType name="Holding">
		<xsd:attribute name="codigo" type="xsd:integer"/>
		<xsd:attribute name="nome" type="xsd:string"/>
	</xsd:complexType>
	
	<xsd:complexType name="Empresa">
		<xsd:attribute name="codigo" type="xsd:integer"/>
		<xsd:attribute name="razaoSocial" type="xsd:string"/>
		<xsd:attribute name="fantasia" type="xsd:string"/>
		<xsd:attribute name="logradouro" type="xsd:string"/>
		<xsd:attribute name="codigoHolding" type="xsd:integer"/>
	</xsd:complexType>
	
	<xsd:complexType name="Loja">
		<xsd:attribute name="codigo" type="xsd:integer"/>
		<xsd:attribute name="nome" type="xsd:string"/>
		<xsd:attribute name="codigoEmpresa" type="xsd:integer"/>
		<xsd:attribute name="dataAbertura" type="xsd:string"/>
		<xsd:attribute name="totalFuncionarios" type="xsd:nonNegativeInteger"/>
	</xsd:complexType>
	
	<xsd:complexType name="Departamento">
		<xsd:attribute name="codigo" type="xsd:integer"/>
		<xsd:attribute name="nome" type="xsd:string"/>
	</xsd:complexType>
	
	<xsd:complexType name="LojaDepartamento">
		<xsd:attribute name="codigo" type="xsd:integer"/>
		<xsd:attribute name="codigoLoja" type="xsd:integer"/>
		<xsd:attribute name="codigoDepartamento" type="xsd:integer"/>
	</xsd:complexType>
	
	<xsd:complexType name="Secao">
		<xsd:attribute name="codigo" type="xsd:integer"/>
		<xsd:attribute name="nome" type="xsd:string"/>
		<xsd:attribute name="codigoDepartamento" type="xsd:integer"/>
	</xsd:complexType>
	
	<xsd:complexType name="Categoria">
		<xsd:attribute name="codigo" type="xsd:integer"/>
		<xsd:attribute name="nome" type="xsd:string"/>
		<xsd:attribute name="codigoSecao" type="xsd:integer"/>
	</xsd:complexType>
	
	<xsd:complexType name="Grade">
		<xsd:attribute name="codigo" type="xsd:integer"/>
		<xsd:attribute name="nome" type="xsd:string"/>
	</xsd:complexType>
	
	<xsd:complexType name="Produto">
		<xsd:attribute name="codigo" type="xsd:integer"/>
		<xsd:attribute name="nome" type="xsd:string"/>
		<xsd:attribute name="codigoCategoria" type="xsd:integer"/>
		<xsd:attribute name="codigoGrade" type="xsd:integer"/>
		<xsd:attribute name="estoqueAtual" type="xsd:nonNegativeInteger"/>
		<xsd:attribute name="estoqueMinimo" type="xsd:nonNegativeInteger"/>
	</xsd:complexType>
	
	<xsd:complexType name="Cor">
		<xsd:attribute name="codigo" type="xsd:integer"/>
		<xsd:attribute name="nome" type="xsd:string"/>
	</xsd:complexType>
	
	<xsd:complexType name="Tamanho">
		<xsd:attribute name="codigo" type="xsd:integer"/>
		<xsd:attribute name="nome" type="xsd:string"/>
	</xsd:complexType>
	
	<xsd:complexType name="GradeItem">
		<xsd:attribute name="codigo" type="xsd:integer"/>
		<xsd:attribute name="nome" type="xsd:string"/>
		<xsd:attribute name="codigoGrade" type="xsd:integer"/>
		<xsd:attribute name="codigoCor" type="xsd:integer"/>
		<xsd:attribute name="codigoTamanho" type="xsd:integer"/>
	</xsd:complexType>
	
	<xsd:complexType name="EstoqueGradeItem">
		<xsd:attribute name="codigo" type="xsd:integer"/>
		<xsd:attribute name="codigoGradeItem" type="xsd:integer"/>
		<xsd:attribute name="codigoProduto" type="xsd:integer"/>
		<xsd:attribute name="codigoLoja" type="xsd:integer"/>
		<xsd:attribute name="estoqueAtual" type="xsd:nonNegativeInteger"/>
		<xsd:attribute name="estoqueMinimo" type="xsd:nonNegativeInteger"/>
	</xsd:complexType>

	<xsd:element name="Negocio">
		<xsd:complexType>
			<xsd:sequence>
			
				<xsd:element name="Holdings">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Holding" type="Holding" maxOccurs="unbounded" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				
				<xsd:element name="Empresas">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Empresa" type="Empresa" maxOccurs="unbounded" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				
				<xsd:element name="Lojas">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Loja" type="Loja" maxOccurs="unbounded" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				
				<xsd:element name="Departamentos">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Departamento" type="Departamento" maxOccurs="unbounded" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				
				<xsd:element name="LojaDepartamentos">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="LojaDepartamento" type="LojaDepartamento" maxOccurs="unbounded" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				
				<xsd:element name="Secoes">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Secao" type="Secao" maxOccurs="unbounded" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				
				<xsd:element name="Categorias">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Categoria" type="Categoria" maxOccurs="unbounded" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				
				<xsd:element name="Grades">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Grade" type="Grade" maxOccurs="unbounded" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				
				<xsd:element name="Produtos">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Produto" type="Produto" maxOccurs="unbounded" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				
				<xsd:element name="Cores">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Cor" type="Cor" maxOccurs="unbounded" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				
				<xsd:element name="Tamanhos">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Tamanho" type="Tamanho" maxOccurs="unbounded" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				
				<xsd:element name="GradeItens">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="GradeItem" type="GradeItem" maxOccurs="unbounded" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				
				<xsd:element name="EstoqueGradeItens">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="EstoqueGradeItem" type="EstoqueGradeItem" maxOccurs="unbounded" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>

			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== wesleyfelipe/ormhibernate/src/main/resources/semiestruturados/Negocio.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Negocio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="Negocio.xsd">
	<Holdings>
		<Holding codigo="1" nome="Grupo MasBahTchê" />
	</Holdings>

	<Empresas>
		<Empresa codigo="1" razaoSocial="Tchê Sapatos Ltda" fantasia="Tchê"
			logradouro="Rua João Vedelino, 145" codigoHolding="1" />
		<Empresa codigo="2" razaoSocial="Juca Sapato Feminino Ltda"
			fantasia="Juca Sapato" logradouro="Rua Zé Teodoro, 666"
			codigoHolding="1" />
	</Empresas>

	<Lojas>
		<Loja codigo="1" codigoEmpresa="1" nome="Filial 1" dataAbertura="01/01/2014"
			totalFuncionarios="16" />
		<Loja codigo="2" codigoEmpresa="1" nome="Filial 1" dataAbertura="15/02/2014"
			totalFuncionarios="30" />
	</Lojas>

	<Departamentos>
		<Departamento codigo="1" nome="Feminino" />
		<Departamento codigo="2" nome="Masculino" />
		<Departamento codigo="3" nome="Infantil" />
	</Departamentos>

	<LojaDepartamentos>
		<LojaDepartamento codigo="1" codigoLoja="1"
			codigoDepartamento="1" />
		<LojaDepartamento codigo="2" codigoLoja="1"
			codigoDepartamento="2" />
		<LojaDepartamento codigo="3" codigoLoja="1"
			codigoDepartamento="3" />
		<LojaDepartamento codigo="4" codigoLoja="2"
			codigoDepartamento="1" />
	</LojaDepartamentos>

	<Secoes>
		<Secao codigo="1" nome="Sapato" codigoDepartamento="1" />
		<Secao codigo="2" nome="Pasta" codigoDepartamento="2" />
	</Secoes>

	<Categorias>
		<Categoria codigo="1" nome="Scarpin" codigoSecao="1" />
		<Categoria codigo="2" nome="Rasteirinha" codigoSecao="1" />
		<Categoria codigo="3" nome="Pasta de mão" codigoSecao="2" />
	</Categorias>

	<Grades>
		<Grade codigo="1" nome="Grade Brasil Feminino" />
		<Grade codigo="2" nome="Grade Brasil Masculino" />
		<Grade codigo="3" nome="Grade Pasta" />
	</Grades>

	<Produtos>
		<Produto codigo="1" nome="Scarpin Velasquez" codigoCategoria="1"
			codigoGrade="1" estoqueAtual="10" estoqueMinimo="10" />
	</Produtos>

	<Cores>
		<Cor codigo="1" nome="Azul" />
		<Cor codigo="2" nome="Preto" />
	</Cores>

	<Tamanhos>
		<Tamanho codigo="1" nome="33" />
		<Tamanho codigo="2" nome="34" />
		<Tamanho codigo="3" nome="35" />
		<Tamanho codigo="4" nome="36" />
		<Tamanho codigo="5" nome="37" />
	</Tamanhos>

	<GradeItens>
		<GradeItem codigo="1" nome="Preto Universo Tamanho 33"
			codigoGrade="1" codigoCor="2" codigoTamanho="1" />
		<GradeItem codigo="2" nome="Preto Universo Tamanho 34"
			codigoGrade="1" codigoCor="2" codigoTamanho="2" />
		<GradeItem codigo="3" nome="Preto Universo Tamanho 35"
			codigoGrade="1" codigoCor="2" codigoTamanho="3" />
		<GradeItem codigo="4" nome="Preto Universo Tamanho 36"
			codigoGrade="1" codigoCor="2" codigoTamanho="4" />
		<GradeItem codigo="5" nome="Preto Universo Tamanho 37"
			codigoGrade="1" codigoCor="2" codigoTamanho="5" />
	</GradeItens>

	<EstoqueGradeItens>
		<EstoqueGradeItem codigo="1" codigoGradeItem="1"
			codigoProduto="1" codigoLoja="1" estoqueAtual="5" estoqueMinimo="2" />
		<EstoqueGradeItem codigo="2" codigoGradeItem="2"
			codigoProduto="1" codigoLoja="1" estoqueAtual="2" estoqueMinimo="5" />
		<EstoqueGradeItem codigo="3" codigoGradeItem="3"
			codigoProduto="1" codigoLoja="1" estoqueAtual="3" estoqueMinimo="3" />
	</EstoqueGradeItens>

</Negocio>
